name: Matt Mad
description: Blogging about stuffs
meta_description: "Blogging about nerd stuffs, personal thoughts, and software development notes"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mattmoya.com'
disqus: 1
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://mattmoya.com'
author:         'Matt Hinczuk'
